import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"
[window]
padding.x = 10
padding.y = 10

decorations = "buttonless"

opacity = 0.81
blur = true

option_as_alt = "OnlyRight"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 16

[shell]
program = "/opt/homebrew/bin/fish"
